services:
  mongodb:
    image: mongo:latest
    container_name: repository_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    networks:
      - repository_network

  repository-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: repository_scanner
    depends_on:
      - mongodb
    volumes:
      - ./output:/app/output
    env_file:
      - .env
    networks:
      - repository_network
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: repository_dashboard
    depends_on:
      - mongodb
    ports:
      - "8501:8501"
    volumes:
      - ./output:/app/output
    env_file:
      - .env
    networks:
      - repository_network
    restart: unless-stopped

networks:
  repository_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 